spring:
  liquibase:
    enabled: true
    
  application:
    name: auth-service
    
  datasource:
    url: jdbc:postgresql://database:5432/freelance
    username: admin
    password: 123
    driverClassName: org.postgresql.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
  main:
    web-application-type: reactive
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8089
