spring:
  liquibase:
    enabled: true
    
  application:
    name: worker-service
    
  datasource:
    url: jdbc:postgresql://database:5432/freelance-worker
    username: admin
    password: 123
    driverClassName: org.postgresql.Driver
    
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8085
